github pages added
LibertyDSNP/example-client pull request #23
Opened 2021-04-30 21:10 UTC by claireolmstead

Purpose
---------------
A description of the purpose for this pull request and weather it is to provide new functionality or fix a bug

Solution
---------------
A descrition of what you have done to implement/fix the above mentioned feature or bug
with @<any other developers who who worked on the PR with you>

Change summary
---------------
* A detailed list of bulleted
* changes that go into detail about
* the specifics of the changes
* to the codebase

Steps to Verify
----------------
1. A numbered list of steps
2. To verify that this feature/bug
3. is now working

Additional details / screenshot
----------------
- Any suplmenental pictures or material
- ![Screenshot]()

2021-04-30 21:26 UTC, Ajaxan requested changes
We will need to setup a blockchain for the example client to fully get this up and working.

2021-04-30 21:26 UTC, Ajaxan commented on src/App.css
> +.Login__block .ant-btn {
Remove .css files.

2021-04-30 21:26 UTC, Ajaxan commented on package.json
> +  "homepage": "http://LibertyDSNP.github.io/example-client",
We still need a blockchain backend for this to work. Currently we've just been using the old demo contracts repo, but we can probably work on something new. Perhaps we can even include that in the repo? We should probably discuss it next week.

2021-05-10 12:37 UTC, wilwade commented on package.json
> +  "homepage": "https://libertydsnp.github.io/example-client/",
This is just me, but I think the home page should still be the github repo.

2021-07-15 19:46 UTC, closed without merging