Feature/create contributing guide 177210106
LibertyDSNP/example-client pull request #3
Opened 2021-03-10 21:17 UTC by Ajaxan

Purpose
---------------
We want to have a guide that will allow any potential contributors to know what to do and what guidelines to follow.

Solution
---------------
Added the contributing.md file to give potential viewers/contributors a guide on how to add to the project.
NOTE: not all the links work. I wasn't sure where the links should go, might need to fix them in a future story.

Change summary
---------------
* Added contributing.ms file
* Sections on reporting and contributing and templates

Steps to Verify
----------------
1. Read Contributing file and make sure it all looks good.

2021-03-22 18:12 UTC, shannonwells approved these changes
lgtm, maybe you & @claireolmstead should both have project settings access if you're leading the charge on it.  @sbendar ?

2021-03-23 13:59 UTC, wilwade requested changes
Two small things and a comment

2021-03-23 13:59 UTC, wilwade commented on CONTRIBUTING.md
> +* [DSNP SDK](https://www.google.com/search) for integration with the DSNP
```suggestion
* [DSNP Spec](https://github.com/LibertyDSNP/spec) for how the DSNP works
* [DSNP SDK](https://github.com/LibertyDSNP/sdk-ts) for integration with the DSNP
```

2021-03-23 13:59 UTC, wilwade commented on CONTRIBUTING.md
> +#### Feature Request Template
You should be able to just add them to .github like https://github.com/LibertyDSNP/sdk-ts/tree/main/.github No additional access should be needed.

2021-03-23 13:59 UTC, wilwade commented on README.md
> +* Install asdf: `asdf install`
asdf is not a requirement, but just a common way to install the correct node version. Not sure how we want to communicate that however.

2021-03-25 12:00 UTC, wilwade commented
@Ajaxan you might want to check out https://github.com/LibertyDSNP/liberty-web/pull/13 as well to see the contributing guide over there and see what crossover we want.

2021-03-29 15:16 UTC, Ajaxan commented
I added links to the liberty web contributing.md (or where it will be, once approved) as a baseline. I kept most of the specific contributing.md for the example client though as it gets more specific.

2021-04-05 13:19 UTC, wilwade approved these changes

2021-04-05 17:04 UTC, enddynayn commented
👍

2021-04-05 17:37 UTC, jvasile commented
Two things we might want to include in this doc:

 * Link to code of conduct (unless that info is in the contributing.md. The link to that was broken, so I'm not sure what the latest status is)
 * Link to forums and an encouragement to pre-flight work with us.  This gets people talking directly to us, which we want.  And it potentially avoids people doing work that we don't want to merge.

2021-04-05 23:55 UTC, merged