add spinner to posts and replies while loading
LibertyDSNP/example-client pull request #54
Opened 2021-08-13 00:09 UTC by claireolmstead

Purpose
---------------
A description of the purpose for this pull request and whether it is to provide new functionality or fix a bug

Solution
---------------
A short description of what you have done to implement/fix the above mentioned feature or bug
with @&lt;any other developers who who worked on the PR with you&gt;

Change summary
---------------
* A detailed list of bulleted
* changes that go into detail about
* the specifics of the changes
* to the codebase

Steps to Verify
----------------
1. A numbered list of steps
2. To verify that this feature/bug
3. is now working

Additional details / screenshot
----------------
- Any supplemental pictures or material
- ![Screenshot]()

2021-08-18 22:15 UTC, claireolmstead commented on src/components/Feed.tsx
> -            onSuccess={() => setIsModalOpen(false)}
can change back

2021-08-18 22:19 UTC, enddynayn approved these changes

2021-08-18 22:36 UTC, claireolmstead commented on src/components/ReplyBlock.tsx
> +  const loading: any = useAppSelector((state) => state.feed.isReplyLoading);
add type

2021-08-18 22:36 UTC, claireolmstead commented on src/redux/slices/feedSlice.ts
> +    replyLoading: (state, isLoading: PayloadAction<any>) => {
change type

2021-08-20 22:03 UTC, shannonwells requested changes
As discussed

2021-08-20 22:03 UTC, shannonwells commented on src/components/Profile.tsx
>      setIsEditing(!isEditing);
Why is profile saving deleted?

2021-08-20 22:03 UTC, shannonwells commented on src/components/NewPost.tsx
> +    console.log(newPostFeedItem);
remove console.log

2021-08-20 22:03 UTC, shannonwells commented on src/redux/slices/feedSlice.ts
> +      if (state.isPostLoading.myIdentifier === newFeedItem.fromId) {
Explanatory comment (as discussed)

2021-08-20 22:03 UTC, shannonwells commented on src/redux/slices/feedSlice.ts
> +  isPostLoading: { loading: false, myIdentifier: undefined },
Can we change myIdentifier to currentUserId?

2021-08-20 22:10 UTC, shannonwells approved these changes
💯 👍

2021-08-20 22:11 UTC, merged